### ISSUE TITLE
Find a way to detect- sense/antisense data

### ISSUE THREAD

**Issue by oganm** [oganm/allenBrain#1]

**Comment by oganm** [comment]
@stripathy Do you know how can i learn if an experiment looks at sense or antisense DNA?

Below ling gives list of Dgkg experiments for instance. The third one is a sense probe. Yet I can't distinguish from the others looking at the xml below

http://api.brain-map.org/api/v2/data/SectionDataSet/query.xml?criteria=products[id$eq1],genes[acronym$eq%27Dgkg%27]&include=genes,section_images

**Comment by stripathy** [comment]
you need to add 'probes' to the query: e.g., http://api.brain-map.org/api/v2/data/SectionDataSet/query.xml?criteria=products[id$eq1],genes[acronym$eq%27Dgkg%27]&include=genes,section_images,probes
